FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Adicione logs para debug
RUN echo "=== Files in /app ===" && ls -la /app/

CMD ["python", "-u", "consumer_notifications.py"]